name = "SuperdropletModel"
uuid = "8d5f9a1e-3b2c-4d5e-8f7a-9b1c2d3e4f5a"
authors = ["Daniel Rothenberg <daniel@danielrothenberg.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.9"
CSV = "0.10"
ProgressMeter = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
