[package]
name = "sd_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.18.3"
plotters = "0.3.7"
rand = "0.9.2"
rand_distr = "0.5.1"
rayon = "1.11.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
